MODEL:
  TYPE: vit
  NAME: fd_pretrain
  DROP_PATH_RATE: 0.3
  VIT:
    EMBED_DIM: 768
    DEPTH: 12
    NUM_HEADS: 12
    USE_APE: False
    USE_RPB: False
    USE_SHARED_RPB: True
    USE_MEAN_POOLING: False
    WITH_CLS_TOKEN: True
DATA:
  IMG_SIZE: 224
  BATCH_SIZE: 128
AUG:
  MIN_SCALE: 0.08
TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 10
  BASE_LR: 3e-4
  WARMUP_LR: 5e-7
  MIN_LR: 5e-6
  WEIGHT_DECAY: 0.05
  CLIP_GRAD: 3.0
DEV:
  PRED_FEAT: DINO
  PRED_FEAT_AFTERNORM: True
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: fd_pretrain__dino_vit_base__img224__300ep
