MODEL:
  TYPE: swin_v2
  NAME: fd_finetune
  DROP_PATH_RATE: 0.4
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 14
DATA:
  IMG_SIZE: 224
  BATCH_SIZE: 64 # here is just a random mistake in our experiments. we believe 128*16=2048 will lead to similar results
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 20
  BASE_LR: 1.25e-3
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-7
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.8
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: fd_finetune__esvit_swin_base__img224__300ep